# Generated by Django 4.1.5 on 2023-02-07 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="users",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.TextField(max_length=100)),
                ("number", models.TextField(max_length=100)),
                ("password", models.TextField(max_length=50)),
            ],
        ),
    ]
