# Generated by Django 4.1.5 on 2023-02-08 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("selfServiceApp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="users",
            name="registered",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="users",
            name="token",
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name="users", name="email", field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="users", name="number", field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="users", name="password", field=models.CharField(max_length=50),
        ),
    ]
