# Generated by Django 4.1.5 on 2023-02-08 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "selfServiceApp",
            "0002_users_registered_users_token_alter_users_email_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="code",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=4)),
            ],
        ),
    ]
