# Generated by Django 4.1.5 on 2023-02-09 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("selfServiceApp", "0004_remove_users_token_users_verificationcode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users",
            name="verificationCode",
            field=models.IntegerField(default=1, max_length=1),
        ),
    ]
