# Generated by Django 4.1.5 on 2023-02-09 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("selfServiceApp", "0005_alter_users_verificationcode"),
    ]

    operations = [
        migrations.AddField(
            model_name="users",
            name="attempts",
            field=models.IntegerField(default=1, max_length=1),
        ),
    ]
