# Generated by Django 4.1.5 on 2023-02-09 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("selfServiceApp", "0006_users_attempts"),
    ]

    operations = [
        migrations.AddField(
            model_name="users",
            name="requestVerificationCode",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="users", name="attempts", field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="users",
            name="verificationCode",
            field=models.CharField(max_length=4),
        ),
    ]
