# Generated by Django 4.1.5 on 2023-02-15 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "selfServiceApp",
            "0007_users_requestverificationcode_alter_users_attempts_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(model_name="users", name="verificationCode",),
    ]
