# Generated by Django 4.1.5 on 2023-02-16 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("selfServiceApp", "0010_cooperates"),
    ]

    operations = [
        migrations.AddField(
            model_name="cooperates",
            name="cr14Path",
            field=models.TextField(default="null"),
        ),
        migrations.AddField(
            model_name="cooperates",
            name="cr6Path",
            field=models.TextField(default="null"),
        ),
        migrations.AddField(
            model_name="cooperates",
            name="proofOfResidencePath",
            field=models.TextField(default="null"),
        ),
        migrations.AlterField(
            model_name="cooperates",
            name="cr14",
            field=models.FileField(default="null", upload_to=""),
        ),
        migrations.AlterField(
            model_name="cooperates",
            name="proofOfResidence",
            field=models.FileField(default="null", upload_to=""),
        ),
    ]
