# Generated by Django 4.1.5 on 2023-02-16 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("selfServiceApp", "0011_cooperates_cr14path_cooperates_cr6path_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cooperates",
            name="cr6",
            field=models.FileField(default="null", upload_to=""),
        ),
    ]
