# Generated by Django 4.1.5 on 2023-02-16 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("selfServiceApp", "0012_alter_cooperates_cr6"),
    ]

    operations = [
        migrations.RemoveField(model_name="cooperates", name="cr14Path",),
        migrations.RemoveField(model_name="cooperates", name="cr6Path",),
        migrations.RemoveField(model_name="cooperates", name="proofOfResidencePath",),
        migrations.AlterField(
            model_name="cooperates",
            name="cr14",
            field=models.FileField(default="null", upload_to="pdfs"),
        ),
        migrations.AlterField(
            model_name="cooperates",
            name="cr6",
            field=models.FileField(default="null", upload_to="pdfs"),
        ),
        migrations.AlterField(
            model_name="cooperates",
            name="proofOfResidence",
            field=models.FileField(default="null", upload_to="pdfs"),
        ),
    ]
