# Generated by Django 4.1.5 on 2023-02-16 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "selfServiceApp",
            "0013_remove_cooperates_cr14path_remove_cooperates_cr6path_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="cooperates",
            name="cdmaNumber",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
