# Generated by Django 4.1.5 on 2023-02-16 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("selfServiceApp", "0014_cooperates_cdmanumber"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cooperates", old_name="number", new_name="gsmNumber",
        ),
        migrations.RenameField(
            model_name="users", old_name="number", new_name="gsmNumber",
        ),
        migrations.AddField(
            model_name="users",
            name="cdmaNumber",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
