# Generated by Django 4.1.5 on 2023-02-18 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("selfServiceApp", "0015_rename_number_cooperates_gsmnumber_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="users", name="attempts",),
        migrations.RemoveField(model_name="users", name="cdmaNumber",),
    ]
