# Generated by Django 4.1.5 on 2023-02-25 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("selfServiceApp", "0017_rename_gsmnumber_users_gsmnumber"),
    ]

    operations = [
        migrations.AddField(
            model_name="cooperates",
            name="alliasNumber",
            field=models.CharField(default=0, max_length=12),
        ),
        migrations.AddField(
            model_name="users",
            name="alliasNumber",
            field=models.CharField(default=0, max_length=12),
        ),
    ]
