# Generated by Django 4.1.5 on 2023-02-26 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("selfServiceApp", "0018_cooperates_alliasnumber_users_alliasnumber"),
    ]

    operations = [
        migrations.AddField(
            model_name="users",
            name="cdmanumber",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="users",
            name="registered",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
