# Generated by Django 4.1.5 on 2023-02-27 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("selfServiceApp", "0019_users_cdmanumber_alter_users_registered"),
    ]

    operations = [
        migrations.AddField(
            model_name="cooperates",
            name="represantativeid",
            field=models.FileField(default="null", upload_to="pdfs"),
        ),
    ]
