# Generated by Django 4.1.5 on 2023-02-27 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("selfServiceApp", "0020_cooperates_represantativeid"),
    ]

    operations = [
        migrations.RemoveField(model_name="cooperates", name="allocatedNumber",),
        migrations.AddField(
            model_name="cooperates",
            name="approved",
            field=models.BooleanField(default=False),
        ),
    ]
