# Generated by Django 4.1.5 on 2023-02-27 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("selfServiceApp", "0021_remove_cooperates_allocatednumber_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="cooperates", name="attempts",),
        migrations.AlterField(
            model_name="cooperates",
            name="approved",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
