# Generated by Django 4.1.5 on 2023-02-27 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("selfServiceApp", "0022_remove_cooperates_attempts_alter_cooperates_approved"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cooperates", old_name="alliasNumber", new_name="alliasnumber",
        ),
        migrations.RenameField(
            model_name="cooperates", old_name="cdmaNumber", new_name="cdmanumber",
        ),
        migrations.RenameField(
            model_name="cooperates", old_name="companyName", new_name="companyname",
        ),
        migrations.RenameField(
            model_name="cooperates",
            old_name="proofOfResidence",
            new_name="proofofresidence",
        ),
        migrations.RenameField(
            model_name="cooperates",
            old_name="requestVerificationCode",
            new_name="requestverificationcode",
        ),
    ]
