# Generated by Django 4.1.5 on 2023-04-13 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selfServiceApp', '0026_rename_alliasnumber_users_alliasnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='alliasnumber',
            field=models.CharField(default='null', max_length=12),
        ),
    ]
